# Generated by Django 3.0.3 on 2020-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, choices=[('Satmak', 'Satmak'), ('Satın Almak', 'Satın Almak'), ('Kiraya Vermek', 'Kiraya Vermek'), ('Kiralamak', 'Kiralamak'), ('Gayrimenkul Değerlemesi', 'Gayrimenkul Değerlemesi'), ('Arsa Yatırımı', 'Arsa Yatırımı'), ('Diğer', 'Diğer')], default='Diğer', max_length=50),
        ),
    ]
